import {
    Button,
    VerticalBox,
    HorizontalBox,
    LineEdit,
    StandardTableView
} from "std-widgets.slint";

import { AddCrawlDialog } from "../components/add-crawl-dialog.slint";

export component CrawlsPage inherits Rectangle {
    in property <[[StandardListViewItem]]> crawls;
    callback request_start_crawl(string, string);
    callback request_delete_crawl(string);

    property <int> right_clicked_crawl_row: -1;

    VerticalBox {
        HorizontalBox {
            height: 40px;
            alignment: start;
            Button {
                text: "Start New Crawl";
                clicked => {
                    add_dialog.show();
                }
            }
        }

        crawl_context_menu := ContextMenuArea {
            StandardTableView {
                width: 100%;
                height: 100%;
                columns: [
                    { title: "ID", width: 50px },
                    { title: "Site", width: 250px },
                    { title: "Started At" },
                ];
                rows: root.crawls;
                row-pointer-event(row-index, event, point) => {
                    if (event.kind == PointerEventKind.down && event.button == PointerEventButton.right) {
                        crawl_context_menu.close();
                        right_clicked_crawl_row = row-index;
                    }
                    if (event.kind == PointerEventKind.up && event.button == PointerEventButton.right) {
                        crawl_context_menu.show(point);
                    }
                }
            }

            Menu {
                MenuItem {
                    title: "Delete Crawl";
                    activated => {
                        if (right_clicked_crawl_row >= 0 && right_clicked_crawl_row < root.crawls.length) {
                            root.request_delete_crawl(root.crawls[right_clicked_crawl_row][0].text);
                        }
                    }
                }
            }
        }
    }

    add_dialog := AddCrawlDialog {
        start(site_id, concurrency) => {
            root.request_start_crawl(site_id, concurrency);
        }
    }
}
