import {
    Button,
    VerticalBox,
    HorizontalBox,
    LineEdit,
    StandardTableView
} from "std-widgets.slint";

export component CrawlsPage inherits VerticalBox {
    in property <[[StandardListViewItem]]> crawls;
    callback request_start_crawl(string, string);
    callback request_delete_crawl(string);

    property <int> right_clicked_crawl_row: -1;

    HorizontalBox {
        height: 40px;
        crawl_site_id := LineEdit {
            placeholder-text: "Site ID";
            width: 100px;
        }

        crawl_concurrency := LineEdit {
            placeholder-text: "Concurrency (default 5)";
            text: "5";
            width: 150px;
        }

        Button {
            text: "Start New Crawl";
            clicked => {
                root.request_start_crawl(crawl_site_id.text, crawl_concurrency.text);
                crawl_site_id.text = "";
            }
        }
    }

    crawl_context_menu := ContextMenuArea {
        StandardTableView {
            width: 100%;
            height: 100%;
            columns: [
                { title: "ID", width: 50px },
                { title: "Site", width: 250px },
                { title: "Started At" },
            ];
            rows: root.crawls;
            row-pointer-event(row-index, event, point) => {
                if (event.kind == PointerEventKind.down && event.button == PointerEventButton.right) {
                    crawl_context_menu.close();
                    right_clicked_crawl_row = row-index;
                }
                if (event.kind == PointerEventKind.up && event.button == PointerEventButton.right) {
                    crawl_context_menu.show(point);
                }
            }
        }

        Menu {
            MenuItem {
                title: "Delete Crawl";
                activated => {
                    if (right_clicked_crawl_row >= 0 && right_clicked_crawl_row < root.crawls.length) {
                        root.request_delete_crawl(root.crawls[right_clicked_crawl_row][0].text);
                    }
                }
            }
        }
    }
}
