import {
    Button,
    VerticalBox,
    HorizontalBox,
    LineEdit,
    StandardTableView,
} from "std-widgets.slint";

import { AddQueryDialog } from "../components/add-query-dialog.slint";

export component QueriesPage inherits Rectangle {
    in property <[[StandardListViewItem]]> queries;
    callback request_add_query(string, string);
    callback request_delete_query(string);

    property <int> right_clicked_query_row: -1;

    VerticalBox {
        HorizontalBox {
            height: 40px;
            alignment: start;
            Button {
                text: "Run Query";
            }
        }

        query_context_menu := ContextMenuArea {
            StandardTableView {
                width: 100%;
                height: 100%;
                columns: [
                    { title: "ID", width: 50px },
                    { title: "Crawl", width: 250px },
                    { title: "Selector" },
                ];
                rows: root.queries;
                row-pointer-event(row-index, event, point) => {
                    if (event.kind == PointerEventKind.down && event.button == PointerEventButton.right) {
                        query_context_menu.close();
                        right_clicked_query_row = row-index;
                    }
                    if (event.kind == PointerEventKind.up && event.button == PointerEventButton.right) {
                        query_context_menu.show(point);
                    }
                }
            }

            Menu {
                MenuItem {
                    title: "Delete Query";
                    activated => {
                        if (right_clicked_query_row >= 0 && right_clicked_query_row < root.queries.length) {
                            root.request_delete_query(root.queries[right_clicked_query_row][0].text);
                        }
                    }
                }
            }
        }
    }

    add_dialog := AddQueryDialog {
        run(crawl_id, selector) => {
            root.request_add_query(crawl_id, selector);
        }
    }
}
