import {
    Button,
    VerticalBox,
    HorizontalBox,
    LineEdit,
    StandardTableView
} from "std-widgets.slint";

export component QueriesPage inherits VerticalBox {
    in property <[[StandardListViewItem]]> queries;
    callback request_add_query(string, string);
    callback request_delete_query(string);

    property <int> right_clicked_query_row: -1;

    HorizontalBox {
        height: 40px;
        query_crawl_id := LineEdit {
            placeholder-text: "Crawl ID";
            width: 100px;
        }

        query_selector := LineEdit {
            placeholder-text: "CSS Selector (e.g., div.content a)";
            width: 300px;
        }

        Button {
            text: "Run Query";
            clicked => {
                root.request_add_query(query_crawl_id.text, query_selector.text);
                query_crawl_id.text = "";
                query_selector.text = "";
            }
        }
    }

    query_context_menu := ContextMenuArea {
        StandardTableView {
            width: 100%;
            height: 100%;
            columns: [
                { title: "ID", width: 50px },
                { title: "Crawl", width: 250px },
                { title: "Selector" },
            ];
            rows: root.queries;
            row-pointer-event(row-index, event, point) => {
                if (event.kind == PointerEventKind.down && event.button == PointerEventButton.right) {
                    query_context_menu.close();
                    right_clicked_query_row = row-index;
                }
                if (event.kind == PointerEventKind.up && event.button == PointerEventButton.right) {
                    query_context_menu.show(point);
                }
            }
        }

        Menu {
            MenuItem {
                title: "Delete Query";
                activated => {
                    if (right_clicked_query_row >= 0 && right_clicked_query_row < root.queries.length) {
                        root.request_delete_query(root.queries[right_clicked_query_row][0].text);
                    }
                }
            }
        }
    }
}
