import { Palette, VerticalBox, HorizontalBox, Button } from "std-widgets.slint";
import { CrawlsGridView } from "../components/crawls-grid-view.slint";
import { QueryView } from "../components/query-view.slint";

export component SiteDetailPage inherits Rectangle {
    in property <string> site-id;
    in property <[[StandardListViewItem]]> crawls;
    in property <[[StandardListViewItem]]> results;

    property <string> selected-crawl-id: "";
    in-out property <int> current-view: 0;  // 0 = crawls grid, 1 = query view

    callback add-crawl-clicked();
    callback delete-crawl-clicked(string);
    callback run-query-clicked(string, string);
    callback crawl-selected(string);
    callback export-csv-clicked();

    VerticalBox {
        padding: 24px;
        spacing: 15px;
        height: 100%;

        // Header
        HorizontalBox {
            padding: 0;
            spacing: 10px;
            alignment: start;

            Text {
              vertical-stretch: 0;
              vertical-alignment: center;
              text: "nikolalazarov.com";
              font-size: 18px;
              font-weight: 600;
            }

            Button {
              text: "Site Settings";
            }
        }

        // Crawls Grid View
        if current-view == 0: CrawlsGridView {
            vertical-stretch: 1;
            crawls: root.crawls;
            add-crawl-clicked => {
                root.add-crawl-clicked();
            }
            delete-crawl-clicked(id) => {
                root.delete-crawl-clicked(id);
            }
            crawl-clicked(id) => {
                root.selected-crawl-id = id;
                root.current-view = 1;
                root.crawl-selected(id);
            }
        }
        
        // Query View
        if current-view == 1: QueryView {
            vertical-stretch: 1;
            selected-crawl-id: root.selected-crawl-id;
            results: root.results;
            back-clicked => {
                root.current-view = 0;
            }
            run-query-clicked(crawl-id, selector) => {
                root.run-query-clicked(crawl-id, selector);
            }
            export-csv-clicked => {
                root.export-csv-clicked();
            }
        }
    }
}
