import { LineEdit, VerticalBox, HorizontalBox, StandardButton } from "std-widgets.slint";

export component AddQueryDialog inherits Dialog {
    callback run(string, string); // crawl_id, selector
    callback cancel-clicked();
    title: "Run New Query";

    // Initial visibility
    visible: false;

    public function show() {
        root.visible = true;
    }

    public function close() {
        root.visible = false;
    }

    property <string> crawl-id-text;
    property <string> selector-text;

    VerticalBox {
        spacing: 15px;
        
        VerticalBox {
            spacing: 5px;
            Text { text: "Crawl ID:"; color: #333; }
            crawl_id_input := LineEdit {
                placeholder-text: "Enter Crawl ID";
                height: 35px;
                edited => { root.crawl-id-text = self.text; }
            }
        }

        VerticalBox {
            spacing: 5px;
            Text { text: "CSS Selector:"; color: #333; }
            selector_input := LineEdit {
                placeholder-text: "div.content a";
                height: 35px;
                edited => { root.selector-text = self.text; }
            }
        }
    }

    StandardButton {
        kind: ok;
        clicked => {
            root.run(crawl_id_input.text, selector_input.text);
            crawl_id_input.text = "";
            selector_input.text = "";
            root.close();
        }
    }

    StandardButton {
        kind: cancel;
        clicked => {
            root.cancel-clicked();
            root.close();
        }
    }
}
